apps/note_it_web/web/router.ex
defmodule NoteItWeb.Router do
  use NoteItWeb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authenticate do
    plug NoteItWeb.Plugs.AuthenticatePlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NoteItWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/signup", SignupController, :index
    post "/signup", SignupController, :signup

    get "/login", LoginController, :index
    post "/login", LoginController, :login

  end

  scope "/", NoteItWeb do
    pipe_through [:browser, :authenticate]

    get "/password", PasswordController, :index
    post "/password", PasswordController, :change

    get "/logout", LoginController, :logout

    get "/groups", GroupController, :list # list groups the user belongs to_
    get "/groups/create", GroupController, :create
    post "/groups/create", GroupController, :add
    get "/groups/g/:name/invite", GroupController, :invite
    post "/groups/g/:name/invite", GroupController, :add_member
    get "/groups/g/:name", GroupController, :details

    get "/notes", NoteController, :list # list notes from all groups the user belongs to
    #get "/notes/create", NoteController, :create
    get "/notes/:id", NoteController, :show
    post "/notes/:id", NoteController, :update
    # get "/notes/:id/delete", NoteController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", NoteItWeb do
  #   pipe_through :api
  # end
end

apps/note_it_web/web/controllers/signup_controller.ex
defmodule NoteItWeb.SignupController do
  use NoteItWeb.Web, :controller

  def index(conn, %{errors: errors}) do
    render(conn, "index.html", changeset: errors)
  end

  def index(conn, _params) do
    changeset = NoteIt.User.changeset(%NoteIt.User{})
    render conn, "index.html", changeset: changeset
  end

  def signup(conn, %{"signup" => user_params}) do
    changeset = NoteIt.User.changeset(%NoteIt.User{}, user_params)

    case NoteIt.UserQueries.create(changeset) do
      {:ok, %{id: id}} ->
        conn
        |> put_session(:current_userid, id)
        |> redirect(to: "/")
      {:error, reasons} ->
        index(conn, %{errors: reasons})
    end
  end
end

apps/note_it_web/web/views/signup_view.ex
defmodule NoteItWeb.SignupView do
  use NoteItWeb.Web, :view
end

apps/note_it_web/web/templates/signup/index.html.eex
<h1> Create an account </h1>
<%= form_for @changeset, signup_path(@conn, :signup), [as: :signup], fn f -> %>
  <div class="form-group">
    <%= label f, :email, "Email" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>
  <div class="form-group">
    <%= label f, :password, "Password" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  <div class="form-group">
    <%= label f, :confirm_password, "Confirm Password" %>
    <%= password_input f, :confirm_password, class: "form-control" %>
    <%= error_tag f, :confirm_password %>
  </div>
  <div class="form-group">
    <%= label f, :name, "Name" %>
    <%= text_input f, :name, class: "form-control" %> <br/>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Signup", class: "btn btn-primary btn-block btn-lg" %>
<% end %>

apps/note_it_web/web/templates/signup/signup.html.eex
<h1> Create an account </h1>
<%= form_for @changeset, signup_path(@conn, :signup), [as: :signup], fn f -> %>
  <div class="form-group">
    <%= label f, :email, "Email" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>
  <div class="form-group">
    <%= label f, :password, "Password" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  <div class="form-group">
    <%= label f, :confirm_password, "Confirm Password" %>
    <%= password_input f, :confirm_password, class: "form-control" %>
    <%= error_tag f, :confirm_password %>
  </div>
  <div class="form-group">
    <%= label f, :name, "Name" %>
    <%= text_input f, :name, class: "form-control" %> <br/>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Signup", class: "btn btn-primary btn-block btn-lg" %>
<% end %>