apps/note_it_web/web/router.ex
defmodule NoteItWeb.Router do
  use NoteItWeb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authenticate do
    plug NoteItWeb.Plugs.AuthenticatePlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NoteItWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/signup", SignupController, :index
    post "/signup", SignupController, :signup

    get "/login", LoginController, :index
    post "/login", LoginController, :login

  end

  scope "/", NoteItWeb do
    pipe_through [:browser, :authenticate]

    get "/password", PasswordController, :index
    post "/password", PasswordController, :change

    get "/logout", LoginController, :logout

    get "/groups", GroupController, :list # list groups the user belongs to_
    get "/groups/create", GroupController, :create
    post "/groups/create", GroupController, :add
    get "/groups/g/:name/invite", GroupController, :invite
    post "/groups/g/:name/invite", GroupController, :add_member
    get "/groups/g/:name", GroupController, :details

    get "/notes", NoteController, :list # list notes from all groups the user belongs to
    #get "/notes/create", NoteController, :create
    get "/notes/:id", NoteController, :show
    post "/notes/:id", NoteController, :update
    # get "/notes/:id/delete", NoteController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", NoteItWeb do
  #   pipe_through :api
  # end
end

apps/note_it_web/web/controllers/note_controller.ex
defmodule NoteItWeb.NoteController do
  use NoteItWeb.Web, :controller

  def list(conn, _params) do
    user = NoteItWeb.Session.current_user(conn)

    notes = NoteIt.NoteQueries.get_by_user(user)
    render conn, "list.html", notes: notes
  end

  def show(conn, %{"id" => id}) do
    user = NoteItWeb.Session.current_user(conn)
    note = NoteIt.NoteQueries.get_by_id(id)

    has_access = user.groups
                  |> Enum.reduce([], fn x, acc -> [x.id | acc] end)
                  |> Enum.member?(note.group.id)

    if (has_access) do
        render conn, "edit.html", note: note
    else
      conn
      |> put_flash(:error, "Access denied")
      |> redirect(to: "/")
    end
  end

end

apps/note_it_web/web/views/note_view.ex
defmodule NoteItWeb.NoteView do
  use NoteItWeb.Web, :view
end

apps/note_it_web/web/templates/note/edit.html.eex
<h1 contenteditable="true"><%= @note.title %></h1>
<div contenteditable="true"><%= @note.note %></div>

apps/note_it_web/web/templates/note/list.html.eex
<h1>Recent Notes
  <a href="#" class="btn btn-primary pull-right">Create</a>
</h1>
<div class="list-group">
  <%= for n <- @notes do %>
    <%= render("summary.html", note: n, conn: @conn) %>
  <% end %>
</div>

apps/note_it_web/web/templates/note/summary.html.eex
<a href="<%= note_path(@conn, :show, @note.id) %>">
  <div class="list-group-item">
    <div class="list-group-item-heading"><%= @note.title %></div>
  </div>
</a>