apps/note_it_web/web/router.ex
defmodule NoteItWeb.Router do
  use NoteItWeb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authenticate do
    plug NoteItWeb.Plugs.AuthenticatePlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NoteItWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/signup", SignupController, :index
    post "/signup", SignupController, :signup

    get "/login", LoginController, :index
    post "/login", LoginController, :login

  end

  scope "/", NoteItWeb do
    pipe_through [:browser, :authenticate]

    get "/password", PasswordController, :index
    post "/password", PasswordController, :change

    get "/logout", LoginController, :logout

    get "/groups", GroupController, :list # list groups the user belongs to_
    get "/groups/create", GroupController, :create
    post "/groups/create", GroupController, :add
    get "/groups/g/:name/invite", GroupController, :invite
    post "/groups/g/:name/invite", GroupController, :add_member
    get "/groups/g/:name", GroupController, :details

    get "/notes", NoteController, :list # list notes from all groups the user belongs to
    #get "/notes/create", NoteController, :create
    get "/notes/:id", NoteController, :show
    post "/notes/:id", NoteController, :update
    # get "/notes/:id/delete", NoteController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", NoteItWeb do
  #   pipe_through :api
  # end
end

apps/note_it_web/web/views/layout_view.ex
defmodule NoteItWeb.LayoutView do
  use NoteItWeb.Web, :view
end

apps/note_it_web/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Note It</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if NoteItWeb.Session.logged_in?(@conn) do %>
              <li><a href="<%= group_path(@conn, :list) %>">My Groups</a></li>
              <li><a href="<%= login_path(@conn, :logout) %>">Logout</a></li>
            <%= else %>
              <li><a href="/signup">Signup</a></li>
              <li><a href="/login">Login</a></li>
            <% end %>
          </ul>
        </nav>
        <a href="/">
          <span class="logo"></span>
        </a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>

        <div class="row marketing">
          <div class="col-lg-6">
            <h4>Resources</h4>
            <ul>
              <li>
                <a href="#how_to">How To</a>
              </li>
              <li>
                <a href="https://github.com/sushilman/note-it">Source</a>
              </li>
            </ul>
          </div>

          <div class="col-lg-6">
            <h4>Help</h4>
            <ul>
              <li>
                <a href="https://raw.githubusercontent.com/sushilman/note-it/master/LICENSE">License</a>
              </li>
            </ul>
          </div>
        </div>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>